
import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rajiv
 */
public class output extends javax.swing.JFrame {

    /**
     * Creates new form output
     */
    public output(String id,String type_,int arms,int temp,double energy,double wt,boolean flag) {
        initComponents();
        this.getContentPane().setBackground(Color.black);
        this.setSize(1000, 419);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        tf1.setEditable(false);
        tf2.setEditable(false);
        tf4.setEditable(false);
        tf5.setEditable(false);
        tf6.setEditable(false);
        tf5.setText(type_);
        tf1.setText(""+wt);
        tf2.setText(""+temp);
        tf6.setText(""+energy);
        type_label.setVisible(false);
        type_label.setText(type_);
        wt_label1.setVisible(false);
        wt_label1.setText(""+wt);
        id_label.setText(id);
        id_label.setVisible(false);
        flag_rb.setVisible(false);
        flag_rb.setSelected(flag);
        //System.out.println(type_);
        //System.out.println(qty);
        //System.out.println(wt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        tf1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf5 = new javax.swing.JTextField();
        type_label = new javax.swing.JLabel();
        wt_label1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        id_label = new javax.swing.JLabel();
        flag_rb = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Temperature (C)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 190, 30));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Duration (Mins)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 190, 30));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Wash Settings");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 190, 30));

        tf2.setBackground(new java.awt.Color(0, 0, 0));
        tf2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf2.setForeground(new java.awt.Color(255, 255, 255));
        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        getContentPane().add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 150, 30));

        tf4.setBackground(new java.awt.Color(0, 0, 0));
        tf4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf4.setForeground(new java.awt.Color(255, 255, 255));
        tf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf4ActionPerformed(evt);
            }
        });
        getContentPane().add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 220, 150, 30));

        tf1.setBackground(new java.awt.Color(0, 0, 0));
        tf1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf1.setForeground(new java.awt.Color(255, 255, 255));
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 150, 30));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Weight (Kgs)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 190, 30));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Type of wash");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 190, 30));

        tf5.setBackground(new java.awt.Color(0, 0, 0));
        tf5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf5.setForeground(new java.awt.Color(255, 255, 255));
        tf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf5ActionPerformed(evt);
            }
        });
        getContentPane().add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 150, 30));
        getContentPane().add(type_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 80, 20));
        getContentPane().add(wt_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 80, 20));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Energy required Watts");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 210, 30));

        tf6.setBackground(new java.awt.Color(0, 0, 0));
        tf6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf6.setForeground(new java.awt.Color(255, 255, 255));
        tf6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf6ActionPerformed(evt);
            }
        });
        getContentPane().add(tf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, 150, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Start wash");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 150, 40));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add user");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 150, 40));
        getContentPane().add(id_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));
        getContentPane().add(flag_rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dishwasher.PNG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents
double energy;

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void tf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf4ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void tf5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf5ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
File file=new File("C:\\Users\\rajiv\\Desktop\\file.csv");
if(file.exists()==false){
try
{
    FileWriter writer=new FileWriter(file);
    writer.append("ID,Type,Weight,Temperature,Duration,Energy Required,Date-Time\n");
    writer.close();
}
catch(Exception e)
{
    System.out.println(e.getMessage());
}
}
int temp=Integer.parseInt(tf2.getText());
int dur=0;
double wt=Double.parseDouble(tf1.getText());
double energy=Double.parseDouble(tf6.getText());
if(wt<3.0)
{
    dur=30;
}
else if(wt>=3.0 && wt<6.0)
{
    dur=35;
}
else if(wt>=6.0 && wt<9.0)
{
    dur=45;
}
else if(wt>=9.0 && wt<12.0)
{
    dur=55;
}
else if(wt>=12.0 )
{
    dur=75;
}
tf4.setText(""+dur);
energy=(energy*dur)/48;
tf6.setText(""+String.format("%.2f", energy));
DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
   LocalDateTime now = LocalDateTime.now();
   String date_time=dtf.format(now);
try
{
    FileWriter writer=new FileWriter(file,true);
    writer.append(""+tf5.getText()+","+wt+","+temp+","+dur+","+energy+","+date_time+"\n");
    writer.close();
}
catch(Exception e)
{
    System.out.println(e.getMessage());
}

// TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void tf6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
double energy_=Double.parseDouble(tf6.getText());
if(flag_rb.isSelected()==false){
        String ID=id_label.getText();
        String url = "jdbc:sqlite:C:\\Rajiv\\SQL\\Sqlite\\dishwasher.db";
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(url);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        String sql = "INSERT INTO processes VALUES('" + ID + "'," + energy_ + ");";
        try {
            Statement stmt = conn.createStatement();
            stmt.executeUpdate(sql);
            System.out.println("Successfully added");
            JOptionPane.showMessageDialog(null, "You have been succesfully registered");
            this.dispose();
            new process().setVisible(true);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
}
else
{
    String ID=id_label.getText();
        String url = "jdbc:sqlite:C:\\Rajiv\\SQL\\Sqlite\\dishwasher.db";
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(url);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        String sql = "INSERT INTO waiting VALUES('" + ID + "'," + energy_ + ");";
        try {
            Statement stmt = conn.createStatement();
            stmt.executeUpdate(sql);
            System.out.println("Successfully added");
            JOptionPane.showMessageDialog(null, "You have been succesfully registered");
            this.dispose();
            new process().setVisible(true);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
}
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
double energy_=Double.parseDouble(tf6.getText());
if(flag_rb.isSelected()==false){
        String ID=id_label.getText();
        String url = "jdbc:sqlite:C:\\Rajiv\\SQL\\Sqlite\\dishwasher.db";
        Connection conn = null;
        try 
        {
            conn = DriverManager.getConnection(url);
        } 
        catch (SQLException e) 
        {
            System.out.println(e.getMessage());
        }
        String sql = "INSERT INTO processes VALUES('" + ID + "'," + energy_ + ");";
        try 
        {
            Statement stmt = conn.createStatement();
            stmt.executeUpdate(sql);
            System.out.println("Successfully added");
            JOptionPane.showMessageDialog(null, "You have been succesfully registered");
            this.dispose();
            new login().setVisible(true);
        } 
        catch (SQLException e) 
        {
            System.out.println(e.getMessage());
        }
}
else
{
    String ID=id_label.getText();
        String url = "jdbc:sqlite:C:\\Rajiv\\SQL\\Sqlite\\dishwasher.db";
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(url);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        String sql = "INSERT INTO waiting VALUES('" + ID + "'," + energy_ + ");";
        try {
            Statement stmt = conn.createStatement();
            stmt.executeUpdate(sql);
            System.out.println("Successfully added");
            JOptionPane.showMessageDialog(null, "You have been succesfully registered");
            this.dispose();
            new login().setVisible(true);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        String id="";
                String type_="";
                int arms=0;
                int temp=0;
                double energy=0.0;
                double wt=0.0;
                boolean flag=false;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new output(id,type_,arms,temp,energy,wt,flag).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton flag_rb;
    private javax.swing.JLabel id_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JLabel type_label;
    private javax.swing.JLabel wt_label1;
    // End of variables declaration//GEN-END:variables
}
